Repository janpeterka/kucharka, pull requests merged in 2022-01, with the labels that each got.

#203 Add event collaboration and event page redesign
  app/controllers/events/edit_events.py
  app/controllers/events/events.py
  app/helpers/general.py
  app/models/__init__.py
  app/models/daily_plans.py
  app/models/events.py
  app/models/recipes.py
  app/models/users.py
  app/models/users_have_event_roles.py
  app/static/css/atomic.css
  app/static/css/components.css
  app/static/css/style.css
  app/templates/events/_delete_or_edit.html.j2
  app/templates/events/_export.html.j2
  app/templates/events/_info.html.j2
  app/templates/events/_more_options.html.j2
  app/templates/events/_sharing.html.j2
  app/templates/events/_warnings.html.j2
  app/templates/events/edit.html.j2
  app/templates/events/edit/_info.html.j2
  app/templates/events/edit/_share_form.html.j2
  app/templates/events/index.html.j2
  app/templates/events/show.html.j2
  app/templates/javascript/_clicker_controller.js
  app/templates/javascript/_set_default_dates_controller.js
  app/templates/javascript/_set_duration_controller.js
  app/templates/javascript/stimulus.js.html
  app/templates/macros/icons.html.j2
  app/templates/macros/render_day_badge.html.j2
  app/templates/macros/render_field.html.j2
  migrations/versions/202112301156_add_event_user_roles.py
Labels: enhancement, UI/UX

#219 Improve event sharing options
  app/controllers/events/edit_events.py
  app/templates/events/_more_options.html.j2
  app/templates/events/_sharing.html.j2
Labels: bugfix

#225 Reload ingredient table when recipe changed
  app/controllers/edit_recipes.py
  app/helpers/base_mixin.py
  app/templates/recipes/edit.html.j2
  app/templates/recipes/edit/_ingredient_table.html.j2
Labels: bugfix

#227 Random code refactors
  app/controllers/recipes.py
Labels: refactor

#231 Enable setting FF by request arg
  kucharka.py
Labels: admin
